baseURL = "/"
languageCode = "nl"
title = "VSA Demo"

disableKinds = ["taxonomy", "term"]

[params]
  linksBron = "https://orthodox-ronl.github.io/bron/"
  linksVsaTooling = "https://orthodox-ronl.github.io/VSA-tooling/"
  linksGithub = "https://github.com/orthodox-ronl/VSA-demo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
